name: AWS OIDC Auth
description: Configure AWS credentials via OIDC
inputs:
  aws_region:
    required: true
  role_arn:
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ inputs.role_arn }}
        aws-region: ${{ inputs.aws_region }}
